name: All Release

on:
  workflow_run:
    workflows: ["Update Chnroute Rules", "Update SmartDNS Rules"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 获取当前日期
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
          
      - name: 打包规则文件
        run: |
          zip -r rules_${{ env.TODAY }}.zip mikrotik/* smartdns/*.txt
          
      - name: 创建Release
        uses: softprops/action-gh-release@v1
        with:
          name: Rules Update ${{ env.TODAY }}
          tag_name: update-${{ env.TODAY }}
          files: rules_${{ env.TODAY }}.zip
          body: |
            规则更新 $(date '+%Y-%m-%d')
            
            包含:
            - MikroTik 规则
            - SmartDNS 规则