name:  Update Chnroute Rules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'mikrotik/**'
      - '.github/workflows/mikrotik_rules.yml'
      - './mikrotik_init_chnroute.sh'

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 更新规则
        run: |
            chmod +x ./mikrotik_init_chnroute.sh
            ./mikrotik_init_chnroute.sh

      - name: 提交更改
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            if [[ -n "$(git status --porcelain)" ]]; then
                git add mikrotik/*
                git commit -m "chore: 更新 chnroute_v4.rsc 规则 $(date '+%Y-%m-%d')"
                git push
            else
                echo "没有规则更新"
            fi
      - name: 上传规则文件作为构件
        uses: actions/upload-artifact@v4
        with:
            name: mikrotik_rules
            path: mikrotik/*
            retention-days: 7