name: Update SmartDNS Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发
  push:
    paths:
      - 'smartdns/**'
      - '.github/workflows/smartdns_rules.yml'

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 更新规则
        run: |
          # 创建临时目录
          mkdir -p smartdns/tmp
          
          # 设置执行权限并运行脚本
          chmod +x ./smartdns/smartdns_init_rules.sh
          ./smartdns/smartdns_init_rules.sh
          
          # 清理临时目录
          rm -rf smartdns/tmp

      - name: 提交更改
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n "$(git status --porcelain)" ]]; then
            git add smartdns/*.txt
            git commit -m "chore: 更新 SmartDNS 规则 $(date '+%Y-%m-%d')"
            git push
          else
            echo "没有规则更新"
          fi

      - name: 上传规则文件作为构件
        uses: actions/upload-artifact@v4
        with:
          name: smartdns-rules
          path: smartdns/*.txt
          retention-days: 7
